#!/bin/bash

echo "Building with direct em++ compilation..."
source /home/shreshth/emsdk/emsdk_env.sh

# Build main app
echo "Building main app..."
em++ -std=c++17 -Isrc \
  src/app/main.cpp \
  src/app/controls.cpp \
  src/physics/schwarzschild_metric.cpp \
  src/physics/hamiltonian.cpp \
  src/numerics/integrator.cpp \
  src/rays/ray_initializer.cpp \
  src/rays/ray_bundle.cpp \
  src/app/worker_bindings.cpp \
  src/render/geometry.cpp \
  src/render/renderer.cpp \
  src/render/camera.cpp \
  -s WASM=1 \
  -s USE_WEBGL2=1 \
  -s FULL_ES3=1 \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s NO_EXIT_RUNTIME=1 \
  -s INVOKE_RUN=1 \
  -s 'EXPORTED_RUNTIME_METHODS=["callMain","ccall","cwrap"]' \
  --bind \
  --shell-file shell.html \
  -o schwarzschild.html

# Build worker module (computation only, no rendering)
echo "Building worker module..."
em++ -std=c++17 -Isrc \
  src/app/worker_bindings.cpp \
  src/physics/schwarzschild_metric.cpp \
  src/physics/hamiltonian.cpp \
  src/numerics/integrator.cpp \
  src/rays/ray_initializer.cpp \
  src/rays/ray_bundle.cpp \
  -s WASM=1 \
  -s ALLOW_MEMORY_GROWTH=1 \
  -s NO_EXIT_RUNTIME=1 \
  -s EXPORT_NAME='WorkerModule' \
  -s 'EXPORTED_RUNTIME_METHODS=["ccall","cwrap"]' \
  --bind \
  -o physics-worker-core.js

# Create worker wrapper that loads the core module
cat > physics-worker.js << 'EOF'
// Physics Worker Wrapper
// This file is auto-generated by build.sh
importScripts('physics-worker-core.js');

let isInitialized = false;

// Use WorkerModule from the core build
const Module = typeof WorkerModule !== 'undefined' ? WorkerModule : self.Module;

if (Module) {
    Module.onRuntimeInitialized = function() {
        isInitialized = true;
        postMessage({ type: 'INIT_COMPLETE' });
    };
} else {
    // Fallback: check if already initialized
    setTimeout(() => {
        if (typeof WorkerModule !== 'undefined' && WorkerModule.compute_geodesic_batch) {
            isInitialized = true;
            postMessage({ type: 'INIT_COMPLETE' });
        }
    }, 100);
}

onmessage = function(e) {
    if (!isInitialized) return;
    
    const msg = e.data;
    
    if (msg.type === 'COMPUTE') {
        const { 
            startIndex, count, 
            observer_r, impact_min, impact_max, 
            num_theta, num_phi, num_impact, 
            use_spherical, num_rays_2d,
            lambda_step, lambda_max,
            requestId
        } = msg.params;
        
        try {
            // Call C++ function from WorkerModule
            const resultVector = Module.compute_geodesic_batch(
                startIndex, count,
                observer_r, impact_min, impact_max,
                num_theta, num_phi, num_impact,
                use_spherical, num_rays_2d,
                lambda_step, lambda_max
            );
            
            // Copy data to Float32Array for transfer
            const size = resultVector.size();
            const data = new Float32Array(size);
            for (let i = 0; i < size; i++) {
                data[i] = resultVector.get(i);
            }
            
            // Clean up C++ vector
            resultVector.delete();
            
            // Post result back (transferable)
            postMessage({
                type: 'RESULT',
                requestId: requestId,
                data: data,
                startIndex: startIndex,
                count: count
            }, [data.buffer]);
            
        } catch (err) {
            console.error("Worker error:", err);
            postMessage({ type: 'ERROR', message: err.toString(), requestId: requestId });
        }
    }
};
EOF

echo "Created physics-worker.js wrapper"

echo ""
echo "Built:"
echo "  - schwarzschild.html (main app)"
echo "  - physics-worker.js (worker module)"
echo ""
echo "Run: emrun schwarzschild.html"
echo ""
echo "Controls:"
echo "  Mouse drag: Rotate camera"
echo "  Scroll: Zoom"
echo "  Up/Down: Observer distance"
echo "  Left/Right: Number of rays"
echo "  [ / ]: Impact parameter range"
echo "  R: Refire rays"
echo "  H: Toggle horizon"
echo "  P: Toggle photon sphere"
echo "  C: Cycle color mode"